In [1]:
import keras.datasets
from sklearn.model_selection import train_test_split
import numpy as np


In [2]:
#X_train, y_train, X_test, y_test = keras.datasets.mnist.load_data()
#(x_train, y_train), (x_test, y_test) = keras.datasets.mnist.load_data()

In [3]:
(X_train, y_train), (X_test, y_test) = keras.datasets.mnist.load_data()
(X_train, y_train), (X_test, y_test)

11490434/11490434 [==============================] - 0s 0us/step


((array([[[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          ...,
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0]],
  
         [[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          ...,
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0]],
  
         [[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          ...,
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0]],
  
         ...,
  
         [[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          ...,
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0]],
  
         [[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0

In [4]:
# Normalize pixel values
X_train = X_train.astype('float32') / 255.0
X_test = X_test.astype('float32') / 255.0

In [5]:
# Convert labels to encoding
num_classes = 10
y_train = keras.utils.to_categorical(y_train, num_classes)
y_test = keras.utils.to_categorical(y_test, num_classes)

### Now you have preprocessed the data and split it into training, validation, and test sets, which can be used for training and evaluating your deep learning models for handwritten digit recognition.

In [6]:
# Split the data into training and testing sets
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.2, random_state=42)
print("Training set shape:", X_train.shape)
print("Validation set shape:", X_val.shape)
print("Test set shape:", X_test.shape)

Training set shape: (48000, 28, 28)
Validation set shape: (12000, 28, 28)
Test set shape: (10000, 28, 28)


In [7]:
(X_train, y_train), (X_test, y_test)

((array([[[0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          ...,
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.]],
  
         [[0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          ...,
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.]],
  
         [[0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          ...,
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.]],
  
         ...,
  
         [[0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          ...,
          [0., 0., 0., ..., 0., 0., 0.],
         

• Implement a baseline model using traditional machine learning algorithms such as logistic regression.


In [8]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
import numpy as np

# Flatten the images
X_train_flat = X_train.reshape(X_train.shape[0], -1)
X_val_flat = X_val.reshape(X_val.shape[0], -1)
X_test_flat = X_test.reshape(X_test.shape[0], -1)

# Initialize the logistic regression model
model = LogisticRegression(max_iter=1000)

# Train the model
model.fit(X_train_flat, np.argmax(y_train, axis=1))

# Make predictions on the validation set
val_predictions = model.predict(X_val_flat)

# Calculate accuracy on the validation set
val_accuracy = accuracy_score(np.argmax(y_val, axis=1), val_predictions)
print("Validation Accuracy:", val_accuracy)

# Make predictions on the test set
test_predictions = model.predict(X_test_flat)

# Calculate accuracy on the test set
test_accuracy = accuracy_score(np.argmax(y_test, axis=1), test_predictions)
print("Test Accuracy:", test_accuracy)

Validation Accuracy: 0.9224166666666667
Test Accuracy: 0.9248


• Evaluate the baseline model's performance using appropriate evaluation metrics.


In [9]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Calculate accuracy on the test set
test_accuracy = accuracy_score(np.argmax(y_test, axis=1), test_predictions)
print("Test Accuracy:", test_accuracy)

# Calculate the confusion matrix
confusion_mat = confusion_matrix(np.argmax(y_test, axis=1), test_predictions)
print("Confusion Matrix:")
print(confusion_mat)

# Generate the classification report
class_report = classification_report(np.argmax(y_test, axis=1), test_predictions)
print("Classification Report:")
print(class_report)

Test Accuracy: 0.9248
Confusion Matrix:
[[ 961    0    1    3    1    5    5    3    1    0]
 [   0 1113    3    2    0    1    4    1   11    0]
 [   7   11  922   18    9    4   14   11   32    4]
 [   4    1   17  921    1   22    4   11   22    7]
 [   1    4    5    3  918    0   10    6    7   28]
 [   8    2    3   38   11  774   15    6   30    5]
 [   9    3    7    2    6   17  911    2    1    0]
 [   0    8   24    8    6    1    0  948    1   32]
 [   8   10    7   23    8   26    9    9  862   12]
 [   8    8    1    9   25    7    1   23    9  918]]
Classification Report:
              precision    recall  f1-score   support

           0       0.96      0.98      0.97       980
           1       0.96      0.98      0.97      1135
           2       0.93      0.89      0.91      1032
           3       0.90      0.91      0.90      1010
           4       0.93      0.93      0.93       982
           5       0.90      0.87      0.89       892
           6       0.94    

## 3. Ensemble of Machine Learning Algorithms (20 marks):

In [12]:
# from sklearn.ensemble import RandomForestClassifier
# from sklearn.svm import SVC
# from sklearn.ensemble import VotingClassifier
# from sklearn.tree import DecisionTreeClassifier

# # Split the data into training and testing sets, allocating only a small portion to training
# X_train_small, _, y_train_small, _ = train_test_split(X_train_flat, y_train, test_size=0.4, random_state=42)

# # Initialize individual models
# decision_tree = DecisionTreeClassifier()
# random_forest = RandomForestClassifier(n_estimators=100)
# svm_model = SVC(kernel='linear', probability=True)

# # Initialize the voting classifier with the individual models
# voting_classifier = VotingClassifier(estimators=[('decision_tree', decision_tree),
#                                                  ('random_forest', random_forest),
#                                                  ('svm', svm_model)],voting='soft')  # Using all available CPU cores

# # Fit the classifier using the smaller training set
# voting_classifier.fit(X_train_small, np.argmax(y_train_small, axis=1))

# # Predict the test data
# test_predictions_ensemble = voting_classifier.predict(X_test_flat)


In [13]:
# class_report_ensemble = classification_report(np.argmax(y_test, axis=1), test_predictions_ensemble)
# print("Classification Report (Ensemble): \n", class_report_ensemble)


Classification Report (Ensemble): 
               precision    recall  f1-score   support

           0       0.95      0.98      0.97       980
           1       0.97      0.98      0.97      1135
           2       0.91      0.90      0.90      1032
           3       0.91      0.90      0.91      1010
           4       0.94      0.93      0.94       982
           5       0.91      0.90      0.90       892
           6       0.94      0.96      0.95       958
           7       0.93      0.94      0.93      1028
           8       0.93      0.90      0.91       974
           9       0.92      0.93      0.92      1009

    accuracy                           0.93     10000
   macro avg       0.93      0.93      0.93     10000
weighted avg       0.93      0.93      0.93     10000



<img src='class_report_ensemble.jpg'>