In [2]:
import keras.datasets
from sklearn.model_selection import train_test_split
import numpy as np


In [3]:
#X_train, y_train, X_test, y_test = keras.datasets.mnist.load_data()
#(x_train, y_train), (x_test, y_test) = keras.datasets.mnist.load_data()

In [4]:
(X_train, y_train), (X_test, y_test) = keras.datasets.mnist.load_data()
(X_train, y_train), (X_test, y_test)

((array([[[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          ...,
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0]],
  
         [[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          ...,
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0]],
  
         [[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          ...,
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0]],
  
         ...,
  
         [[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          ...,
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0]],
  
         [[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0

In [5]:
# Normalize pixel values
X_train = X_train.astype('float32') / 255.0
X_test = X_test.astype('float32') / 255.0

In [6]:
# Convert labels to encoding
num_classes = 10
y_train = keras.utils.to_categorical(y_train, num_classes)
y_test = keras.utils.to_categorical(y_test, num_classes)

### Now you have preprocessed the data and split it into training, validation, and test sets, which can be used for training and evaluating your deep learning models for handwritten digit recognition.

In [7]:
# Split the data into training and testing sets
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.2, random_state=42)
print("Training set shape:", X_train.shape)
print("Validation set shape:", X_val.shape)
print("Test set shape:", X_test.shape)

Training set shape: (48000, 28, 28)
Validation set shape: (12000, 28, 28)
Test set shape: (10000, 28, 28)


In [8]:
(X_train, y_train), (X_test, y_test)

((array([[[0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          ...,
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.]],
  
         [[0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          ...,
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.]],
  
         [[0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          ...,
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.]],
  
         ...,
  
         [[0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          ...,
          [0., 0., 0., ..., 0., 0., 0.],
         

• Implement a baseline model using traditional machine learning algorithms such as logistic regression.


In [9]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
import numpy as np

# Flatten the images
X_train_flat = X_train.reshape(X_train.shape[0], -1)
X_val_flat = X_val.reshape(X_val.shape[0], -1)
X_test_flat = X_test.reshape(X_test.shape[0], -1)

# Initialize the logistic regression model
model = LogisticRegression(max_iter=1000)

# Train the model
model.fit(X_train_flat, np.argmax(y_train, axis=1))

# Make predictions on the validation set
val_predictions = model.predict(X_val_flat)

# Calculate accuracy on the validation set
val_accuracy = accuracy_score(np.argmax(y_val, axis=1), val_predictions)
print("Validation Accuracy:", val_accuracy)

# Make predictions on the test set
test_predictions = model.predict(X_test_flat)

# Calculate accuracy on the test set
test_accuracy = accuracy_score(np.argmax(y_test, axis=1), test_predictions)
print("Test Accuracy:", test_accuracy)

Validation Accuracy: 0.9221666666666667
Test Accuracy: 0.924


• Evaluate the baseline model's performance using appropriate evaluation metrics.


In [10]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Calculate accuracy on the test set
test_accuracy = accuracy_score(np.argmax(y_test, axis=1), test_predictions)
print("Test Accuracy:", test_accuracy)

# Calculate the confusion matrix
confusion_mat = confusion_matrix(np.argmax(y_test, axis=1), test_predictions)
print("Confusion Matrix:")
print(confusion_mat)

# Generate the classification report
class_report = classification_report(np.argmax(y_test, axis=1), test_predictions)
print("Classification Report:")
print(class_report)

Test Accuracy: 0.924
Confusion Matrix:
[[ 961    0    1    3    1    4    6    3    1    0]
 [   0 1113    2    2    0    1    4    1   12    0]
 [   7   11  921   18    9    4   13   11   34    4]
 [   3    1   17  921    1   23    3   10   22    9]
 [   1    4    6    3  919    0   10    6    7   26]
 [   8    2    3   38   11  771   16    7   31    5]
 [   9    3    9    2    6   17  910    2    0    0]
 [   0    8   24    9    5    1    0  948    1   32]
 [   8   10    7   24    8   28    9    9  856   15]
 [   8    8    1    9   24    7    1   22    9  920]]
Classification Report:
              precision    recall  f1-score   support

           0       0.96      0.98      0.97       980
           1       0.96      0.98      0.97      1135
           2       0.93      0.89      0.91      1032
           3       0.90      0.91      0.90      1010
           4       0.93      0.94      0.93       982
           5       0.90      0.86      0.88       892
           6       0.94     

##  Ensemble of Machine Learning Algorithms:

In [ ]:
# from sklearn.ensemble import RandomForestClassifier
# from sklearn.svm import SVC
# from sklearn.ensemble import VotingClassifier
# from sklearn.tree import DecisionTreeClassifier

# # Split the data into training and testing sets, allocating only a small portion to training
# X_train_small, _, y_train_small, _ = train_test_split(X_train_flat, y_train, test_size=0.1, random_state=42)

# # Initialize individual models
# decision_tree = DecisionTreeClassifier()
# random_forest = RandomForestClassifier(n_estimators=100)
# svm_model = SVC(kernel='linear', probability=True)

# # Initialize the voting classifier with the individual models
# voting_classifier = VotingClassifier(estimators=[('decision_tree', decision_tree),
#                                                  ('random_forest', random_forest),
#                                                  ('svm', svm_model)],voting='soft', n_jobs=-1)  # Using all available CPU cores

# # Fit the classifier using the smaller training set
# voting_classifier.fit(X_train_small, np.argmax(y_train_small, axis=1))

# # Predict the test data
# test_predictions_ensemble = voting_classifier.predict(X_test_flat)

In [ ]:
# class_report_ensemble = classification_report(np.argmax(y_test, axis=1), test_predictions_ensemble)
# print("Classification Report (Ensemble): \n", class_report_ensemble)

<img src='class_report_ensemble.jpg'>

### Neural Network Model Design:
• Design and implement multiple neural network architectures for handwritten digit recognition.

In [13]:
from tensorflow import keras
from tensorflow.keras import layers

### Multi-Layer Perceptron (MLP)

In [11]:
#Creating the model MLP 
model = keras.models.Sequential()
model.add(keras.layers.Flatten(input_shape=[28, 28]))
model.add(keras.layers.Dense(300, activation="relu"))
model.add(keras.layers.Dense(100, activation="relu"))
model.add(keras.layers.Dense(10, activation="softmax"))


c:\Users\Intithar Alhazmi\miniconda3\Lib\site-packages\keras\src\layers\reshaping\flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


### Deep Convolutional Neural Network (CNN)

In [14]:
##Creating the model deep CNN 
model_deep_cnn = keras.Sequential([
    layers.Conv2D(32, kernel_size=(3, 3), activation="relu", input_shape=(28, 28, 1)),
    layers.Conv2D(64, kernel_size=(3, 3), activation="relu"),
    layers.MaxPooling2D(pool_size=(2, 2)),
    layers.Dropout(0.25),
    layers.Flatten(),
    layers.Dense(128, activation="relu"),
    layers.Dropout(0.5),
    layers.Dense(10, activation="softmax")
])

c:\Users\Intithar Alhazmi\miniconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:99: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(


###Compile and train the models

In [15]:
# Compile the models
model.compile(optimizer="adam", loss="categorical_crossentropy", metrics=["accuracy"])
model_deep_cnn.compile(optimizer="adam", loss="categorical_crossentropy", metrics=["accuracy"])

In [16]:
# Train the models
model.fit(X_train, y_train, batch_size=128, epochs=10, validation_data=(X_test, y_test))
model_deep_cnn.fit(X_train, y_train, batch_size=128, epochs=10, validation_data=(X_test, y_test))

Epoch 1/10
375/375 ━━━━━━━━━━━━━━━━━━━━ 7s 12ms/step - accuracy: 0.8435 - loss: 0.5547 - val_accuracy: 0.9565 - val_loss: 0.1408
Epoch 2/10
375/375 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - accuracy: 0.9640 - loss: 0.1250 - val_accuracy: 0.9661 - val_loss: 0.1093
Epoch 3/10
375/375 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - accuracy: 0.9760 - loss: 0.0787 - val_accuracy: 0.9697 - val_loss: 0.1007
Epoch 4/10
375/375 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - accuracy: 0.9849 - loss: 0.0514 - val_accuracy: 0.9758 - val_loss: 0.0760
Epoch 5/10
375/375 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - accuracy: 0.9877 - loss: 0.0389 - val_accuracy: 0.9755 - val_loss: 0.0803
Epoch 6/10
375/375 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - accuracy: 0.9925 - loss: 0.0264 - val_accuracy: 0.9737 - val_loss: 0.0827
Epoch 7/10
375/375 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - accuracy: 0.9935 - loss: 0.0219 - val_accuracy: 0.9751 - val_loss: 0.0800
Epoch 8/10
375/375 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - accuracy: 0.9958 - loss: 0.0155 - val_accuracy: 

• Experiment with different network architectures, including variations in the number of layers, neurons per layer, activation functions, and 
### regularization techniques.

In [17]:
from tensorflow.keras.regularizers import l2

# Creating the model MLP
model = keras.models.Sequential()
model.add(keras.layers.Flatten(input_shape=[28, 28]))
model.add(keras.layers.Dense(300, activation="relu"))
model.add(keras.layers.Dropout(0.5))  # Dropout regularization with 50% dropout 
model.add(keras.layers.Dense(100, activation="relu"))
model.add(keras.layers.Dense(10, activation="softmax"))

c:\Users\Intithar Alhazmi\miniconda3\Lib\site-packages\keras\src\layers\reshaping\flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [19]:
# Creating the model deep CNN
model_deep_cnn = keras.Sequential([
    layers.Conv2D(32, kernel_size=(3, 3), activation="relu", input_shape=(28, 28, 1)),
    layers.Conv2D(64, kernel_size=(3, 3), activation="relu"),
    layers.MaxPooling2D(pool_size=(2, 2)),
    layers.Dropout(0.25),  # Dropout regularization with 25% dropout 
    layers.Flatten(),
    layers.Dense(128, activation="relu", kernel_regularizer=keras.regularizers.l2(0.001)),  # L2 regularization with regularization of 0.001
    layers.Dropout(0.25),  # Dropout regularization with 50% dropout 
    layers.Dense(10, activation="softmax")
])

• Train each neural network model on the MNIST dataset and evaluate its performance and report overfitting.

In [20]:
# Compile the models
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
model_deep_cnn.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# Train the models
model.fit(X_train, y_train, epochs=10, validation_data=(X_val, y_val))
model_deep_cnn.fit(X_train, y_train, epochs=10, validation_data=(X_val, y_val))

Epoch 1/10
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 15s 8ms/step - accuracy: 0.8293 - loss: 0.5430 - val_accuracy: 0.9532 - val_loss: 0.1487
Epoch 2/10
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 44s 29ms/step - accuracy: 0.9440 - loss: 0.1825 - val_accuracy: 0.9662 - val_loss: 0.1051
Epoch 3/10
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 58s 13ms/step - accuracy: 0.9542 - loss: 0.1422 - val_accuracy: 0.9718 - val_loss: 0.0924
Epoch 4/10
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 13s 9ms/step - accuracy: 0.9612 - loss: 0.1198 - val_accuracy: 0.9763 - val_loss: 0.0841
Epoch 5/10
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 11s 7ms/step - accuracy: 0.9665 - loss: 0.1076 - val_accuracy: 0.9751 - val_loss: 0.0791
Epoch 6/10
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 12s 8ms/step - accuracy: 0.9686 - loss: 0.0988 - val_accuracy: 0.9760 - val_loss: 0.0824
Epoch 7/10
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 10s 7ms/step - accuracy: 0.9721 - loss: 0.0919 - val_accuracy: 0.9769 - val_loss: 0.0797
Epoch 8/10
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 11s 7ms/step - accuracy: 0.9729 - loss:

• Train each neural network model on the MNIST dataset and evaluate its performance and report overfitting.

In [21]:
# Evaluate the models 
mlp_test_loss, mlp_test_accuracy = model.evaluate(X_test, y_test)
deep_cnn_test_loss, deep_cnn_test_accuracy = model_deep_cnn.evaluate(X_test, y_test)

print("MLP Test Loss:", mlp_test_loss)
print("MLP Test Accuracy:", mlp_test_accuracy)
print("Deep CNN Test Loss:", deep_cnn_test_loss)
print("Deep CNN Test Accuracy:", deep_cnn_test_accuracy)

313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9762 - loss: 0.0880
313/313 ━━━━━━━━━━━━━━━━━━━━ 5s 15ms/step - accuracy: 0.9859 - loss: 0.1545
MLP Test Loss: 0.072828508913517
MLP Test Accuracy: 0.98089998960495
Deep CNN Test Loss: 0.14771850407123566
Deep CNN Test Accuracy: 0.987500011920929
